export const WILAYAS = [
  { code: '01', name: 'Adrar' },
  { code: '02', name: 'Chlef' },
  { code: '03', name: 'Laghouat' },
  { code: '04', name: 'Oum El Bouaghi' },
  { code: '05', name: 'Batna' },
  { code: '06', name: 'Béjaïa' },
  { code: '07', name: 'Biskra' },
  { code: '08', name: 'Béchar' },
  { code: '09', name: 'Blida' },
  { code: '10', name: 'Bouira' },
  { code: '11', name: 'Tamanrasset' },
  { code: '12', name: 'Tébessa' },
  { code: '13', name: 'Tlemcen' },
  { code: '14', name: 'Tiaret' },
  { code: '15', name: 'Tizi Ouzou' },
  { code: '16', name: 'Alger' },
  { code: '17', name: 'Djelfa' },
  { code: '18', name: 'Jijel' },
  { code: '19', name: 'Sétif' },
  { code: '20', name: 'Saïda' },
  { code: '21', name: 'Skikda' },
  { code: '22', name: 'Sidi Bel Abbès' },
  { code: '23', name: 'Annaba' },
  { code: '24', name: 'Guelma' },
  { code: '25', name: 'Constantine' },
  { code: '26', name: 'Médéa' },
  { code: '27', name: 'Mostaganem' },
  { code: '28', name: "M'Sila" },
  { code: '29', name: 'Mascara' },
  { code: '30', name: 'Ouargla' },
  { code: '31', name: 'Oran' },
  { code: '32', name: 'El Bayadh' },
  { code: '33', name: 'Illizi' },
  { code: '34', name: 'Bordj Bou Arreridj' },
  { code: '35', name: 'Boumerdès' },
  { code: '36', name: 'El Tarf' },
  { code: '37', name: 'Tindouf' },
  { code: '38', name: 'Tissemsilt' },
  { code: '39', name: 'El Oued' },
  { code: '40', name: 'Khenchela' },
  { code: '41', name: 'Souk Ahras' },
  { code: '42', name: 'Tipaza' },
  { code: '43', name: 'Mila' },
  { code: '44', name: 'Aïn Defla' },
  { code: '45', name: 'Naâma' },
  { code: '46', name: 'Aïn Témouchent' },
  { code: '47', name: 'Ghardaïa' },
  { code: '48', name: 'Relizane' },
  { code: '49', name: 'Timimoun' },
  { code: '50', name: 'Bordj Badji Mokhtar' },
  { code: '51', name: 'Ouled Djellal' },
  { code: '52', name: 'Béni Abbès' },
  { code: '53', name: 'In Salah' },
  { code: '54', name: 'In Guezzam' },
  { code: '55', name: 'Touggourt' },
  { code: '56', name: 'Djanet' },
  { code: '57', name: "M'Ghair" },
  { code: '58', name: 'El Meniaa' },
]

export const ORDER_STATUSES = {
  new: { label: 'New', color: 'blue', bg: 'bg-blue-100', text: 'text-blue-700' },
  confirmed: { label: 'Confirmed', color: 'indigo', bg: 'bg-indigo-100', text: 'text-indigo-700' },
  preparing: { label: 'Preparing', color: 'yellow', bg: 'bg-yellow-100', text: 'text-yellow-700' },
  delivered: { label: 'Delivered', color: 'green', bg: 'bg-green-100', text: 'text-green-700' },
  cancelled: { label: 'Cancelled', color: 'red', bg: 'bg-red-100', text: 'text-red-700' },
}

export const PRODUCT_CATEGORIES = [
  { id: 'cases', name: 'Cases & Covers', slug: 'cases' },
  { id: 'chargers', name: 'Chargers & Cables', slug: 'chargers' },
  { id: 'audio', name: 'Audio & Headphones', slug: 'audio' },
  { id: 'protection', name: 'Screen Protection', slug: 'protection' },
  { id: 'smart', name: 'Smart Accessories', slug: 'smart' },
  { id: 'power', name: 'Power Banks', slug: 'power' },
  { id: 'mounts', name: 'Mounts & Stands', slug: 'mounts' },
  { id: 'other', name: 'Other', slug: 'other' },
]

export const ADMIN_ROLES = {
  super_admin: 'Super Admin',
  admin: 'Admin',
}

export const ROUTES = {
  HOME: '/',
  PRODUCTS: '/products',
  PRODUCT_DETAIL: '/products/:id',
  CART: '/cart',
  CHECKOUT: '/checkout',
  ORDER_CONFIRMATION: '/order-confirmation/:id',
  ADMIN_LOGIN: '/admin/login',
  ADMIN_DASHBOARD: '/admin',
  ADMIN_PRODUCTS: '/admin/products',
  ADMIN_ORDERS: '/admin/orders',
  ADMIN_USERS: '/admin/users',
  ADMIN_SETTINGS: '/admin/settings',
}
